// Data

const strains = [
  {id:'ww',name:'White Widow',bank:'Various Banks',type:'hybrid',typeName:'Híbrida',
   thc:'20–22%',cbd:'<1%',flower:'8–9 sem',yieldIn:'450–550',yieldOut:'550–600 g/pl',
   height:'80–110cm',diff:'Fácil',system:'RDWC / DWC',technique:'ScrOG / LST',
   ecVeg:1.0,ecFlower:2.0,ecPeak:2.2,ph:'5.8–6.3',phFlower:'6.0–6.5',tempWater:18,
   vegW:4,flowerW:9,
   desc:'La cepa clásica por excelencia. Equilibrio perfecto entre facilidad de cultivo y rendimiento. Alta producción de resina, excelente para extracción. Muy estable en DWC/RDWC. Tolera variaciones de EC mejor que la mayoría.',
   ambNotes:'Resistente a variaciones de temperatura. En Castelló aguanta bien veranos cálidos si la solución se mantiene fresca.',
   nutriProfile:{veg:'Equilibrado N-P-K 3-1-2. Responde bien a CalMag en hidro.',flower:'Subir P-K semana 5-6. PK 13/14 en semanas 6-7. Flush 10-14 días.'},
   tags:['Resina','Clásica','Equilibrada','Fácil hidro']},

  {id:'ak47',name:'AK-47',bank:'Serious Seeds',type:'hybrid',typeName:'Híbrida',
   thc:'20–23%',cbd:'<1%',flower:'8–9 sem',yieldIn:'500–600',yieldOut:'650 g/pl',
   height:'90–120cm',diff:'Moderada',system:'RDWC / NFT',technique:'ScrOG + LST',
   ecVeg:1.1,ecFlower:2.2,ecPeak:2.4,ph:'5.8–6.2',phFlower:'6.0–6.4',tempWater:19,
   vegW:4,flowerW:9,
   desc:'Sativa dominante de ciclo corto. Perfil aromático complejo con notas de madera y tierra. Excelente en hidro por su vigor y asimilación de nutrientes elevada. Requiere ScrOG obligatorio por su tendencia vertical.',
   ambNotes:'Sensible a temperaturas nocturnas <16°C. Ventilación cruzada importante en floración para evitar botrytis en cogollos compactos.',
   nutriProfile:{veg:'Alta demanda N fase inicial. Micronutrientes quelatados importantes.',flower:'Responde muy bien a estimuladores de floración. Bajada gradual de N desde semana 3.'},
   tags:['Aromática','Sativa-dom','Alta EC','ScrOG ideal']},

  {id:'northl',name:'Northern Lights',bank:'Sensi Seeds',type:'indica',typeName:'Índica',
   thc:'18–20%',cbd:'<1%',flower:'7–8 sem',yieldIn:'500–600',yieldOut:'600 g/pl',
   height:'80–100cm',diff:'Muy fácil',system:'DWC / RDWC',technique:'SOG / ScrOG',
   ecVeg:1.0,ecFlower:1.9,ecPeak:2.0,ph:'5.5–6.2',phFlower:'5.8–6.3',tempWater:18,
   vegW:3,flowerW:8,
   desc:'Índica pura legendaria. La más sencilla en sistema hidropónico. Ciclo corto, compacta y con excelente relación esfuerzo/resultado. Perfecta primera cepa en DWC. Sin stretch en floración.',
   ambNotes:'Tolera temperaturas más bajas que otras cepas (mínimo 16°C). Ideal para cultivos en zonas con inviernos frescos.',
   nutriProfile:{veg:'Dieta ligera. Sensible a sobrealimentación. EC máxima en veg: 1.4',flower:'Floración rápida, no sobrealimentar. EC máxima 2.0 suficiente.'},
   tags:['Compacta','SOG ideal','Indoor','Principiantes']},

  {id:'amnesia',name:'Amnesia Haze',bank:'Dinafem / HSO',type:'sativa',typeName:'Sativa',
   thc:'20–22%',cbd:'<1%',flower:'10–11 sem',yieldIn:'600–650',yieldOut:'700 g/pl',
   height:'120–160cm',diff:'Avanzada',system:'RDWC',technique:'ScrOG + Topping',
   ecVeg:1.2,ecFlower:2.3,ecPeak:2.6,ph:'5.8–6.5',phFlower:'6.0–6.5',tempWater:20,
   vegW:5,flowerW:11,
   desc:'Sativa de alto rendimiento y ciclo largo. En RDWC el ciclo se reduce 1-2 semanas vs tierra. Requiere control de altura mediante ScrOG desde semana 2 de veg. Aroma muy intenso: filtro de carbón imprescindible.',
   ambNotes:'En Castelló adaptar el cultivo para evitar la floración en agosto (temperatura extrema). Mejor iniciar en otoño para florar en noviembre-diciembre.',
   nutriProfile:{veg:'Gran demanda de N. Tolera EC alta (hasta 1.6 en veg avanzada).',flower:'Alta tolerancia a EC elevada. PK 13/14 semanas 7-8. Flush mínimo 14 días.'},
   tags:['Alta producción','Sativa pura','Aroma intenso','RDWC óptimo']},

  {id:'gg4',name:'Gorilla Glue #4',bank:'GG Strains / Barney\'s',type:'hybrid',typeName:'Híbrida',
   thc:'25–30%',cbd:'<1%',flower:'8–9 sem',yieldIn:'550–600',yieldOut:'700 g/pl',
   height:'90–130cm',diff:'Moderada',system:'RDWC',technique:'ScrOG',
   ecVeg:1.2,ecFlower:2.4,ecPeak:2.6,ph:'5.8–6.3',phFlower:'6.0–6.5',tempWater:19,
   vegW:4,flowerW:9,
   desc:'Genética moderna de altísima potencia y resina extrema. En hidropónico desarrolla un vigor impresionante. Tolera EC muy alta en floración. Los filtros de carbón se saturan rápido por la resina — planificar mantenimiento.',
   ambNotes:'Muy resinosa: los vapores de terpenos pueden saturar el espacio. Ventilación reforzada en floración semanas 5-8.',
   nutriProfile:{veg:'Vigorosa, demanda alta de N y CalMag.',flower:'Aguanta hasta EC 2.6 sin quema. Amplificadores de resina muy efectivos.'},
   tags:['Alta potencia','Resina XXL','Popular','EC alta']},

  {id:'critk',name:'Critical Kush',bank:"Barney's Farm",type:'indica',typeName:'Índica',
   thc:'20–25%',cbd:'1–2%',flower:'8 sem',yieldIn:'550–600',yieldOut:'700 g/pl',
   height:'80–100cm',diff:'Fácil',system:'RDWC / DWC',technique:'SOG / ScrOG',
   ecVeg:1.1,ecFlower:2.1,ecPeak:2.3,ph:'5.8–6.3',phFlower:'6.0–6.5',tempWater:19,
   vegW:3,flowerW:8,
   desc:'Índica potente con CBD apreciable (1-2%). Muy productiva en hidropónico y compacta. Resistente al calor mediterráneo. Cogollos extremadamente densos — vigilar botrytis con HR >55% en floración.',
   ambNotes:'Excelente para Castelló: tolera el calor estival mejor que otras índicas. Defoliar en semana 4 de floración para mejorar ventilación de cogollos.',
   nutriProfile:{veg:'Dieta moderada. CalMag importante en hidro duro.',flower:'Cogollos densos responden a PK booster. No exceder EC 2.3.'},
   tags:['CBD','Mediterráneo','Productiva','Compacta']},

  {id:'northlauto',name:'Northern Lights Auto',bank:'Greenhouse Seeds',type:'auto',typeName:'Autoflo.',
   thc:'15–18%',cbd:'<1%',flower:'70 días total',yieldIn:'400–500',yieldOut:'200–300 g/pl',
   height:'60–80cm',diff:'Muy fácil',system:'DWC',technique:'LST suave',
   ecVeg:0.8,ecFlower:1.6,ecPeak:1.8,ph:'5.5–6.2',phFlower:'5.8–6.3',tempWater:18,
   vegW:3,flowerW:6,
   desc:'La autofloreciente perfecta para iniciarse en DWC. Sin cambio de fotoperiodo: 20h luz todo el ciclo. Sensible a sobrealimentación — empezar con EC baja. Ciclos cortos permiten 4-5 cosechas/año.',
   ambNotes:'20h luz todo el ciclo. No hacer topping en autos — solo LST suave desde semana 2.',
   nutriProfile:{veg:'EC muy baja (0.6–0.8). Sensible a exceso de N.',flower:'Floración automática. EC máxima 1.8. Flush solo 5-7 días.'},
   tags:['Automática','Ciclo corto','4-5/año','Sin fotoperiodo']},

  {id:'ggauto',name:'Gorilla Zkittlez Auto',bank:'Fast Buds',type:'auto',typeName:'Autoflo.',
   thc:'22–26%',cbd:'<1%',flower:'63–70 días',yieldIn:'500–600',yieldOut:'250–350 g/pl',
   height:'80–120cm',diff:'Moderada',system:'DWC / RDWC',technique:'ScrOG + LST',
   ecVeg:1.0,ecFlower:2.0,ecPeak:2.2,ph:'5.8–6.3',phFlower:'6.0–6.5',tempWater:19,
   vegW:4,flowerW:6,
   desc:'Auto de alta potencia y producción XXL para ser autofloreciente. Una de las más demandadas 2024-2025. En DWC consigue tiempos récord. ScrOG adaptado a autos desde semana 2 sin topping.',
   ambNotes:'Responde excepcionalmente a 20h luz todo el ciclo. No bajar de 18h aunque sea auto.',
   nutriProfile:{veg:'EC moderada-alta para auto (hasta 1.2). Tolera bien los nutrientes.',flower:'Potencia alta, aguanta EC 2.0–2.2. PK booster semanas 5-6.'},
   tags:['Auto potente','Alta producción','Modernas','2024-25']}
];

const nutrients = [
  {rank:1,name:'CANNA Aqua Vega/Flores A+B',brand:'CANNA (Países Bajos)',score:5,
   system:'RDWC / DWC / NFT (recirculación)',level:'Todos los niveles',organic:false,
   price:'€€€',
   desc:'Formulado específicamente para sistemas de recirculación cerrada (RDWC, DWC). Mantiene pH y EC estables durante días, reduciendo ajustes. El estándar de referencia en la industria del cannabis hidropónico europeo. Dos componentes A+B evitan precipitación de nutrientes.',
   phases:{germ:'No usar (agua RO pura)',veg:'Aqua Vega A+B: 4+4 mL/L. EC base: 0.8–1.4',flower:'Aqua Flores A+B: 4+4 mL/L. EC: 1.6–2.4',flush:'Canna Flush: 2 mL/L'},
   aditivos:['Rhizotonic (raíces)', 'Cannazym (enzimas)', 'PK 13/14 (semanas 6-7)', 'Boost Accelerator'],
   pHrange:'5.5–6.5',ECrange:'0.8–2.4 mS/cm',
   pros:'Estabilidad de pH excepcional en recirculación. Resultados muy consistentes. Disponible en toda España.',
   cons:'Precio elevado. No apto para sistemas de drenaje libre (usar Hydro en ese caso).'},

  {rank:2,name:'General Hydroponics Flora Series',brand:'GHE / Terra Aquatica',score:5,
   system:'Todos los sistemas hidropónicos',level:'Principiantes a avanzados',organic:false,
   price:'€€',
   desc:'El sistema de 3 partes más usado del mundo desde 1976. FloraGro + FloraMicro + FloraBloom permiten personalización total por fase. Usado por NASA, universidades y productores profesionales. Relación calidad-precio imbatible. Ahora comercializado como Terra Aquatica en Europa.',
   phases:{germ:'FloraMicro: 1.5 mL/L. EC: 0.4–0.6',veg:'Micro 2.5 + Gro 3 + Bloom 1 mL/L. EC: 0.8–1.4',flower:'Micro 2.5 + Gro 1 + Bloom 3 mL/L. EC: 1.4–2.2',flush:'FloraKleen: 2 mL/L'},
   aditivos:['Pro Roots (enraizante)', 'Diamond Nectar (ácidos húmicos)', 'Ripen (maduración)', 'Bio Bloom'],
   pHrange:'5.5–6.5',ECrange:'0.4–2.4 mS/cm',
   pros:'Máxima flexibilidad y personalización. Precio accesible. Enorme comunidad de soporte. Tablas detalladas por fase.',
   cons:'Requiere mezclar 3 productos por cada solución. Curva de aprendizaje inicial.'},

  {rank:3,name:'Advanced Nutrients pH Perfect Sensi',brand:'Advanced Nutrients (Canadá)',score:4,
   system:'DWC / RDWC / Aeroponía',level:'Principiantes',organic:false,
   price:'€€€€',
   desc:'Tecnología de auto-corrección de pH integrada (pH Perfect®). El sistema ajusta el pH automáticamente entre 5.5 y 6.5 en agua de calidad. Ideal para cultivadores que tienen dificultades con el control de pH. Formulación en 2 partes: Grow A+B y Bloom A+B.',
   phases:{germ:'No usar (demasiado potente)',veg:'Sensi Grow A+B: 4 mL/L c/u. EC: 1.0–1.4',flower:'Sensi Bloom A+B: 4 mL/L c/u. EC: 1.6–2.4',flush:'Final Phase: 2 mL/L'},
   aditivos:['Voodoo Juice (microbios)', 'Big Bud (floración)', 'Overdrive (maduración)', 'B-52 (vitaminas)'],
   pHrange:'Auto 5.5–6.5 (con agua pura)',ECrange:'1.0–2.4 mS/cm',
   pros:'Control de pH automático. Formulaciones específicas para cannabis. Soporte técnico excepcional.',
   cons:'Precio muy elevado. pH Perfect solo funciona con agua RO o baja en minerales. No usar con agua dura.'},

  {rank:4,name:'Plagron Hydro A+B',brand:'Plagron (Países Bajos)',score:4,
   system:'DWC / RDWC / Lana de roca',level:'Intermedio',organic:false,
   price:'€€',
   desc:'Fertilizante de dos componentes equilibrado para hidroponía. Excelente relación calidad-precio. Muy utilizado en España. Fórmula estable que no precipita fácilmente. Compatibilidad probada con la mayoría de aditivos del mercado.',
   phases:{germ:'Agua RO + CalMag. EC: 0.3',veg:'Hydro A+B: 3.5+3.5 mL/L. EC: 0.8–1.4',flower:'Hydro A+B: 3.5+3.5 mL/L + PK booster. EC: 1.4–2.2',flush:'Agua RO. EC: 0.1–0.3'},
   aditivos:['Green Sensation (floración)', 'Sugar Royal (terpenos)', 'Vita Race (foliar)', 'Alga Bloom'],
   pHrange:'5.5–6.5',ECrange:'0.8–2.2 mS/cm',
   pros:'Excelente precio. Muy disponible en growshops españoles. Fórmula estable y fiable.',
   cons:'Menos precisión que CANNA o AN. Sistema de 2 partes con menos personalización.'},

  {rank:5,name:'House & Garden Aqua Flakes',brand:'House & Garden (Países Bajos)',score:4,
   system:'DWC / RDWC (recirculación)',level:'Avanzado',organic:false,
   price:'€€€',
   desc:'Nutriente premium especialmente formulado para sistemas de recirculación con agua dura. Muy popular entre cultivadores profesionales europeos. Sistema A+B con alta pureza de minerales. Produce cogollos extremadamente densos y aromáticos.',
   phases:{germ:'No usar',veg:'Aqua Flakes A+B: 4+4 mL/L. EC: 0.8–1.4',flower:'Aqua Flakes A+B: 4+4 mL/L. EC: 1.6–2.6',flush:'Drip Clean: 0.1 mL/L'},
   aditivos:['Roots Excelurator (raíces)', 'Shooting Powder (floración)', 'Top Shooter', 'Bud XL'],
   pHrange:'5.5–6.5',ECrange:'0.8–2.6 mS/cm',
   pros:'Formulación premium de alta pureza. Excellent en agua dura. Cogollos muy densos.',
   cons:'Precio elevado. Disponibilidad limitada en tiendas locales españolas. Menos documentación en español.'},

  {rank:6,name:'BioBizz Fish·Mix + Bloom',brand:'BioBizz (Países Bajos)',score:3,
   system:'Coco / DWC con precaución',level:'Principiantes (orgánico)',organic:true,
   price:'€€',
   desc:'La opción 100% orgánica más popular. Basado en extractos de pescado y algas marinas. Produce cogollos con sabor y aroma superiores al finalizar. Más complejo de controlar en hidropónico puro — riesgo de microorganismos en el depósito. Ideal con coco como complemento al sistema.',
   phases:{germ:'Worm Humus: 1 mL/L',veg:'Fish·Mix: 4 mL/L + Grow: 2 mL/L. EC: 0.8–1.2',flower:'Bloom: 4 mL/L + Top·Max: 2 mL/L. EC: 1.2–1.8',flush:'Agua limpia 10 días'},
   aditivos:['Top·Max (floración)', 'Alg·A·Mic (estrés)', 'Bio·Heaven (aminoácidos)', 'CalMag'],
   pHrange:'6.0–7.0 (orgánico)',ECrange:'0.8–1.8 mS/cm',
   pros:'100% orgánico. Sabor final excepcional. Sin riesgo de sobrealimentación con minerales.',
   cons:'No ideal para hidropónico puro — bacterias en depósito. pH más alto requerido. Menos rendimiento que mineral.'},

  {rank:7,name:'Remo Nutrients SuperVeg/Bloom',brand:'Remo Nutrients (Canadá)',score:3,
   system:'DWC / RDWC / Coco',level:'Intermedio',organic:false,
   price:'€€€',
   desc:'Sistema completo de 7 productos desarrollado por el cultivador Remo Collussi. Muy popular en la comunidad cannábica anglosajona y con creciente presencia en Europa. Formulación equilibrada con énfasis en densidad y sabor de cogollos.',
   phases:{germ:'AstroFlower: 1 mL/L',veg:'SuperVeg: 3 mL/L. EC: 0.8–1.4',flower:'Bloom: 3 + Magnifical: 2 mL/L. EC: 1.6–2.2',flush:'No especificado — agua RO'},
   aditivos:['Magnifical (Ca+Mg)', 'Natures Candy (terpenos)', 'Velokelp (algas)', 'AstroFlower'],
   pHrange:'5.5–6.5',ECrange:'0.8–2.2 mS/cm',
   pros:'Sistema completo e integrado. Buen soporte comunidad. Resultados muy consistentes.',
   cons:'Sistema propietario (7 productos). Precio total del kit elevado. Poca disponibilidad en España.'},

  {rank:8,name:'Atami Wilma / Hydro Nutrients',brand:'Atami B\'cuzz (Países Bajos)',score:3,
   system:'DWC / RDWC / NFT',level:'Intermedio',organic:false,
   price:'€€',
   desc:'Línea europea de nutrientes hidropónicos con larga trayectoria. Especialmente buena relación calidad-precio para el mercado español. Sistema A+B sencillo con aditivos opcionales. Buen rendimiento en agua de red tratada.',
   phases:{germ:'Coco A+B: 1+1 mL/L',veg:'Hydro A+B: 3+3 mL/L. EC: 0.8–1.4',flower:'Hydro A+B: 3+3 mL/L + PK Booster. EC: 1.4–2.0',flush:'Root Stimulator + agua'},
   aditivos:['Root Stimulator', 'Bloom Stimulator', 'B\'cuzz Coco', 'Silic Rock'],
   pHrange:'5.5–6.5',ECrange:'0.8–2.0 mS/cm',
   pros:'Muy accesible en growshops españoles. Precio razonable. Simple de usar.',
   cons:'Rendimientos algo inferiores a CANNA o GHE con las mismas condiciones.'},

  {rank:9,name:'Shogun Katana Roots / Shogun',brand:'Shogun Fertilisers (UK)',score:3,
   system:'DWC / RDWC / Aeroponía',level:'Avanzado',organic:false,
   price:'€€€',
   desc:'Nutrientes premium del Reino Unido con tecnología SmartZen®. Formulados para maximizar el DO y la absorción en sistemas de alta oxigenación. Especialmente efectivos en aeroponía y RDWC con alta recirculación. Cogollos muy densos y compactos.',
   phases:{germ:'Katana Roots: 1 mL/L',veg:'Shogun Grow A+B: 3+3 mL/L. EC: 0.8–1.4',flower:'Shogun Bloom A+B: 3+3 mL/L. EC: 1.6–2.4',flush:'Dragon Force (2 sem)'},
   aditivos:['Katana Roots', 'CalMag', 'Sumo Boost', 'Dragon Force (flush activo)'],
   pHrange:'5.5–6.5',ECrange:'0.8–2.4 mS/cm',
   pros:'Tecnología avanzada SmartZen. Excelente en RDWC. Dragon Force mejora el flush activo.',
   cons:'Poca disponibilidad en España. Documentación principalmente en inglés.'},

  {rank:10,name:'Masterblend 4-18-38 + CalMag',brand:'Masterblend (EEUU)',score:3,
   system:'DWC / NFT / Goteo',level:'Avanzado (DIY)',organic:false,
   price:'€',
   desc:'El fertilizante en polvo más económico del mercado. Utilizado en agricultura profesional y adaptado al cannabis por la comunidad. Requiere mezcla precisa con nitrato cálcico y sulfato de magnesio. Curva de aprendizaje alta pero coste mínimo: ideal para setups grandes.',
   phases:{germ:'No usar',veg:'Mezcla: 2.4g Masterblend + 2.4g CaNO3 + 1.2g MgSO4 por 10L. EC: 0.8–1.2',flower:'Ajustar ratio P-K subiendo Masterblend. EC: 1.4–2.2',flush:'Agua RO pura'},
   aditivos:['Nitrato cálcico (Ca)', 'Sulfato de magnesio (Mg)', 'Silicato de potasio (Si)', 'Opcional: ácidos húmicos'],
   pHrange:'5.5–6.5',ECrange:'0.8–2.2 mS/cm',
   pros:'Precio imbatible (€/kg). Control total de la fórmula. Ideal para escalar producción.',
   cons:'Requiere balanza de precisión. Más cálculo/preparación. No apto para principiantes.'}
];

const waterProfiles = {
  destilada: { label: 'Destilada', baseEC: 0.02, basePH: 6.0, calmagMlL: 0.6 },
  RO: { label: 'Ósmosis', baseEC: 0.1, basePH: 6.1, calmagMlL: 0.4 },
  red: { label: 'Grifo', baseEC: 0.45, basePH: 7.2, calmagMlL: 0.1 },
};

const doseByNutrientRank = {
  1: { baseMlL: 3.6, supplementsMlL: 0.5 },
  2: { baseMlL: 3.0, supplementsMlL: 0.6 },
  3: { baseMlL: 3.8, supplementsMlL: 0.6 },
  4: { baseMlL: 3.2, supplementsMlL: 0.5 },
  5: { baseMlL: 3.9, supplementsMlL: 0.7 },
  6: { baseMlL: 2.8, supplementsMlL: 0.4 },
  7: { baseMlL: 3.1, supplementsMlL: 0.6 },
  8: { baseMlL: 3.0, supplementsMlL: 0.5 },
  9: { baseMlL: 3.3, supplementsMlL: 0.6 },
  10: { baseMlL: 2.4, supplementsMlL: 0.4 },
};
